# Generated by Django 3.2 on 2021-05-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
