# Generated by Django 3.2 on 2021-05-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_home', '0002_auto_20210505_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='weblink',
            field=models.URLField(),
        ),
    ]
