# Generated by Django 3.2 on 2021-10-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_home', '0003_alter_post_weblink'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
