# Generated by Django 3.2 on 2021-10-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f_home', '0004_auto_20211023_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='weblink',
            new_name='websitelink',
        ),
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
    ]
