# Generated by Django 3.2 on 2021-10-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_home', '0006_auto_20211025_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(max_length=30)),
            ],
        ),
    ]
