# Generated by Django 3.2 on 2021-10-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_home', '0007_companysize'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.CharField(blank=True, choices=[('0', '0-25'), ('1', '25-50'), ('2', '50-100'), ('3', '100-250'), ('4', '250-350'), ('5', '350-500'), ('6', '500-750'), ('7', '750-1000')], default='Select size', max_length=100),
        ),
    ]
