# Generated by Django 3.2 on 2021-10-25 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f_home', '0008_post_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estd',
            field=models.CharField(default='No data available', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='f_home.companysize'),
        ),
    ]
