# Generated by Django 3.2 on 2021-10-26 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f_home', '0009_auto_20211025_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='post',
            name='estd',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='f_home.companysize'),
        ),
    ]
