# Generated by Django 3.2 on 2021-10-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_home', '0010_auto_20211026_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tech',
            field=models.ManyToManyField(to='f_home.LanguageStack'),
        ),
    ]
