# Generated by Django 3.2 on 2021-10-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f_home', '0011_post_tech'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
