# Generated by Django 3.2 on 2021-10-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_home', '0012_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagestack',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
